import play.sbt.PlayImport.*
import play.sbt.routes.RoutesKeys
import sbt.Keys.*
import sbt.Tests.{Group, SubProcess}
import sbt.*
import uk.gov.hmrc.DefaultBuildSettings.*
import uk.gov.hmrc.sbtdistributables.SbtDistributablesPlugin
import uk.gov.hmrc.{DefaultBuildSettings, SbtAutoBuildPlugin}

import scala.collection.Seq

lazy val appName = "voa-property-linking"

lazy val playSettings: Seq[Setting[_]] = Seq(
  RoutesKeys.routesImport ++= Seq(
    "uk.gov.hmrc.voapropertylinking.binders.propertylinks._",
    "uk.gov.hmrc.voapropertylinking.binders.clients._",
    "uk.gov.hmrc.voapropertylinking.binders.propertylinks.temp._",
    "scala.language.reflectiveCalls",
    "models._"
  )
)

val defaultPort = 9524

ThisBuild / majorVersion := 0
ThisBuild / scalaVersion := "2.13.12"
ThisBuild / excludeDependencies ++= Seq(
  // As of Play 3.0, groupId has changed to org.playframework; exclude transitive dependencies to the old artifacts
  // Specifically affects play-json-extensions dependency
  ExclusionRule(organization = "com.typesafe.play")
)

lazy val scoverageSettings: Seq[Def.Setting[_ >: String with Double with Boolean]] = {
  // Semicolon-separated list of regexs matching classes to exclude
  import scoverage.ScoverageKeys
  Seq(
    ScoverageKeys.coverageExcludedPackages := "<empty>;.*Reverse.*;Reverse.*;views.*;uk.gov.hmrc.voapropertylinking.config.*;.*\\.temp\\..*;.*\\.test\\..*;poc.view.*;poc.uk.gov.hmrc.voapropertylinking.config.*;.*(AuthService|BuildInfo|Routes).*",
    ScoverageKeys.coverageMinimumStmtTotal := 85,
    ScoverageKeys.coverageFailOnMinimum := true,
    ScoverageKeys.coverageHighlighting := true
  )
}

lazy val microservice: Project = Project(appName, file("."))
  .enablePlugins(PlayScala, SbtDistributablesPlugin)
  .disablePlugins(JUnitXmlReportPlugin)
  .settings(playSettings *)
  .settings(scoverageSettings *)
  .settings(scalaSettings *)
  .settings(defaultSettings() *)
  .settings(PlayKeys.playDefaultPort := defaultPort)
  .settings(majorVersion := 0)
  .settings(
    libraryDependencies ++= compileDependencies ++ testDependencies,
    retrieveManaged := true)

lazy val it = project
  .enablePlugins(PlayScala)
  .dependsOn(microservice % "test->test") // the "test->test" allows reusing test code and test dependencies
  .settings(DefaultBuildSettings.itSettings())
  .settings(libraryDependencies ++= testDependencies)
  .settings(Test / classLoaderLayeringStrategy := ClassLoaderLayeringStrategy.AllLibraryJars)

scalacOptions ++= Seq("-unchecked", "-deprecation", "-feature")

// silence all warnings on autogenerated files
scalacOptions += "-Wconf:src=routes/.*:s"
scalacOptions += "-Wconf:cat=unused-imports&src=html/.*:s"

val bootstrapPlayVersion = "9.5.0"
val hmrcMongoVersion = "2.2.0"

val compileDependencies = Seq(
  ws,
  guice,
  "uk.gov.hmrc"        %% "bootstrap-backend-play-30" % bootstrapPlayVersion,
  "uk.gov.hmrc.mongo"  %% "hmrc-mongo-play-30"        % hmrcMongoVersion,
  "org.typelevel"      %% "cats-core"                 % "2.12.0",
  "uk.gov.hmrc"        %% "uri-template"              % "1.14.0",
  "ai.x"               %% "play-json-extensions"      % "0.42.0",
  "org.apache.commons" % "commons-text"               % "1.12.0"
)

val testDependencies = Seq(
  "uk.gov.hmrc"            %% "bootstrap-test-play-30"  % bootstrapPlayVersion  % Test,
  "org.pegdown"            % "pegdown"                  % "1.6.0"               % Test,
  "org.mockito"            % "mockito-core"             % "5.14.1"              % Test,
  "org.scalacheck"         %% "scalacheck"              % "1.18.1"              % Test,
  "uk.gov.hmrc.mongo"      %% "hmrc-mongo-test-play-30" % hmrcMongoVersion      % Test
)

addCommandAlias("precommit", ";scalafmt;test:scalafmt;it/test:scalafmt;coverage;test;it/test;coverageReport")
